version: '3'

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api
    container_name: api
    restart: always
    tty: True
    working_dir: /api
    ports:
      - 8000:8000

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "smitdb"
      POSTGRES_USER: "gray"
      POSTGRES_PASSWORD: "qm7hFSIW"
    ports:
      - "5432:5432"